Correct device check
This commit fixes a bug for devices where `serial` is empty. 

Without fix it crashes:
```
Traceback (most recent call last):
  File "/Users/mh/Locks/UWB/python-sniffer/apps/sniffer/1_sniffer_listener.py", line 76, in <module>
    main()
    ~~~~^^
  File "/Users/mh/Locks/UWB/python-sniffer/apps/sniffer/1_sniffer_listener.py", line 29, in main
    dongle_list = scan_uwb_dongle_devices()
  File "/Users/mh/Locks/UWB/python-sniffer/drivers/forthink_uwb_dongle.py", line 32, in scan_uwb_dongle_devices
    ftdi_device_locations = Ft4222hDeviceManager.get_device_locations()
  File "/Users/mh/Locks/UWB/python-sniffer/drivers/nxp_ft4222h.py", line 36, in get_device_locations
    if device_info['id'] == 67330076 and device_info['serial'][-1] == 65:
                                         ~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: index out of range
```

Since the intention of the logic is to check for `FT4222 A`, we should not check in `serial`, but in `description`.

For reference, this is `device_info` on such device: 
`{'index': 0, 'flags': 2, 'type': 10, 'id': 67330076, 'location': 82433, 'serial': b'', 'description': b'FT4222 A', 'handle': 0}`

This could also fix https://github.com/forthink-xyz/uwb-sniffer-wireshark/issues/1 if you generate the executables with this change.